//Post Parameters Body (Correct parameters):
POST http://localhost:8080/items/buy
Content-Type: application/x-www-form-urlencoded

customerId=3&itemId=8

###
//Post Parameters Body (INCORRECT parameters):
POST http://localhost:8080/items/buy
Content-Type: application/x-www-form-urlencoded

customerId=4&itemId=8

###
//Post Text Body:
POST http://localhost:8080/items
Content-Type: application/json

{
  "name": "Äpple",
  "price": "10"
}

###